module.exports = {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    safelist: [
        "max-h-max",
        "p-4",
        "border-b-[3px]",
        "lg:border-l-[3px]",
        "bg-primariomedio",
        "border-primario",
    ],
    theme: {
        colors: {
            primario: "#075E52",
            primariohover: "#0A3B34",
            primariopastel: "#D2E8E8",
            primariomedio: "#8CBBBB",
            primariofondo: "#E0EEEB",
            errortexto: "#D32F2F",
            errorfondo: "#FFCDD2",
            beige: "#647C76",
            azul: "#30557D",
            fondo: "#dedede",
            blanco: "#FFFFFF",
            gris: "#c5c5c5",
            grisoscuro: "#7c7c7c",
            blancohover: "#B0B0B0",
            negro: "#2C2C2C",
            negrohover: "#494949",
            editar: "#FB923C",
            editarhover: "#F97316",
            eliminar: "#DC2626",
            eliminarhover: "#B91C1C",
            guardar: "#0EA5E9",
            guardarhover: "#0284C7",
        },
        fontFamily: {
            titulo: ["Domine", "sans-serif"],
            cuerpo: ["Noticia Text", "serif"],
            ui: ["Libre Franklin", "sans-serif"],
        },
        extend: {},
    },
    plugins: [],
};
